### ISSUE TITLE
I added the french language in version 4.1.9

### ISSUE THREAD

**Issue by zen2cool** [xsmo/Image-Uploader-and-Browser-for-CKEditor#12]
Hello, I added the french language in version 4.1.9

Who can I send it to to add it?

[imageuploader4.1.9_with_french.zip](https://github.com/xsmo/Image-Uploader-and-Browser-for-CKEditor/files/3984372/imageuploader4.1.9_with_french.zip)

**Comment by xsmo** [comment]
Simply create a pull request.

**Comment by zen2cool** [comment]
Not possible it's blur ...
