### ISSUE TITLE
Add image padding

### ISSUE THREAD

**Issue by 2braincells2go** [xsmo/Image-Uploader-and-Browser-for-CKEditor#2]
Nice plugin!

Was wondering if possible to add image padding?

Left-top-right-bottom padding would be very nice addition. Seems the text at times appears too close to image, making it hard to read.

Thanks much,

Woody

**Comment by xsmo** [comment]
For the thumbnails or for the image preview when double clicking?

**Comment by 2braincells2go** [comment]
My bad, should have been clearer:)

Yes, when double clicking the inserted image. Some pages/templates have CSS padding built-in but for those that do not, be nice to have padding options.

Cheers!

**Comment by CAVAh** [comment]
I fixed it, I will send tomorrow.

**Comment by 2braincells2go** [comment]
Many many thanks!

**Comment by xsmo** [comment]
Please check out this blog post:
http://www.maleck.org/us/news.php

There will be a new version of the image browser with lots of new features and the image preview will be also redesigned, fixing the padding!

Could you please email me using the contact form from the link above?

**Comment by CAVAh** [comment]
Yes, I will be sending it now.

**Comment by 2braincells2go** [comment]
@olavo1965 Is there any way to get your mod? Like to try it.

**Comment by xsmo** [comment]
@Woody Have you received my answer to your mail?

**Comment by 2braincells2go** [comment]
@xsmo Let me check the account when I get classroom settled down
